version: '3'
services:
  selenoid:
    network_mode: bridge
    image: aerokube/selenoid:latest-release
    volumes:
    - "$PWD:/etc/selenoid"
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "$PWD/mochawesome-report/video:/opt/selenoid/video"
    - "$PWD/support:/home/selenium/uploadTesting"
    environment:
    - OVERRIDE_VIDEO_OUTPUT_DIR=$PWD/mochawesome-report/video
    command: [ "-timeout","310s","-limit","4","-enable-file-upload"]
    ports:
    - "4444:4444"
  selenoid-ui:
    image: "aerokube/selenoid-ui"
    network_mode: bridge
    links:
    - selenoid
    ports:
    - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
